package com.liuml.apptimelimiter.ipc

import android.net.Uri

object RuleContract {
    const val AUTHORITY = "com.liuml.apptimelimiter.rules"
    val CONTENT_URI: Uri = Uri.parse("content://$AUTHORITY")

    const val METHOD_GET_RULE = "get_rule"
    const val METHOD_APPEND_LOG = "append_log"
    const val METHOD_RECORD_USAGE = "record_usage"
    const val METHOD_VIBRATE_WARNING = "vibrate_warning"
    const val METHOD_CLAIM_GROUP_COOLDOWN = "claim_group_cooldown"
    const val METHOD_CREATE_BREAK_SESSION = "create_break_session"
    const val METHOD_CONSUME_BREAK_SESSION = "consume_break_session"

    const val KEY_OK = "ok"
    const val KEY_ENABLED = "enabled"
    const val KEY_SESSION_PLANNING_ENABLED = "session_planning_enabled"
    const val KEY_LIMIT_SECONDS = "limit_seconds"
    const val KEY_MODE = "mode"
    const val KEY_DAILY_ENABLED = "daily_enabled"
    const val KEY_DAILY_LIMIT_SECONDS = "daily_limit_seconds"
    const val KEY_PER_LAUNCH_ENABLED = "per_launch_enabled"
    const val KEY_PER_LAUNCH_LIMIT_SECONDS = "per_launch_limit_seconds"
    const val KEY_SCHEDULE_ENABLED = "schedule_enabled"
    const val KEY_SCHEDULE_MODE = "schedule_mode"
    const val KEY_SCHEDULE_WINDOWS = "schedule_windows"
    const val KEY_COOLDOWN_ENABLED = "cooldown_enabled"
    const val KEY_COOLDOWN_SECONDS = "cooldown_seconds"
    const val KEY_VERSION = "version"
    const val KEY_EXIT_WARNING_ENABLED = "exit_warning_enabled"
    const val KEY_FULL_SCREEN_EXIT_WARNING_ENABLED = "full_screen_exit_warning_enabled"
    const val KEY_EXIT_WARNING_VIBRATION_ENABLED = "exit_warning_vibration_enabled"
    const val KEY_LANGUAGE_MODE = "language_mode"
    const val KEY_EXTENSION_SECONDS = "extension_seconds"
    const val KEY_DIAGNOSTICS_ENABLED = "diagnostics_enabled"
    const val KEY_USAGE_STATS_ENABLED = "usage_stats_enabled"
    const val KEY_LIMIT_ENFORCEMENT_MODE = "limit_enforcement_mode"
    const val KEY_SYSTEM_TODAY_USED_MS = "system_today_used_ms"
    const val KEY_SYSTEM_USAGE_MEASURED_AT_ELAPSED_MS =
        "system_usage_measured_at_elapsed_ms"
    const val KEY_SYSTEM_USAGE_PENDING = "system_usage_pending"
    const val KEY_GROUP_ENABLED = "group_enabled"
    const val KEY_GROUP_ID = "group_id"
    const val KEY_GROUP_NAME = "group_name"
    const val KEY_GROUP_DAILY_ENABLED = "group_daily_enabled"
    const val KEY_GROUP_DAILY_LIMIT_SECONDS = "group_daily_limit_seconds"
    const val KEY_GROUP_TODAY_USED_MS = "group_today_used_ms"
    const val KEY_GROUP_PER_LAUNCH_ENABLED = "group_per_launch_enabled"
    const val KEY_GROUP_PER_LAUNCH_LIMIT_SECONDS = "group_per_launch_limit_seconds"
    const val KEY_GROUP_SCHEDULE_ENABLED = "group_schedule_enabled"
    const val KEY_GROUP_SCHEDULE_MODE = "group_schedule_mode"
    const val KEY_GROUP_SCHEDULE_WINDOWS = "group_schedule_windows"
    const val KEY_GROUP_COOLDOWN_ENABLED = "group_cooldown_enabled"
    const val KEY_GROUP_COOLDOWN_SECONDS = "group_cooldown_seconds"
    const val KEY_GROUP_VERSION = "group_version"
    const val KEY_GROUP_DAY_TOKEN = "group_day_token"
    const val KEY_GROUP_MEASURED_AT_ELAPSED_MS = "group_measured_at_elapsed_ms"
    const val KEY_GROUP_COOLDOWN_STARTED_AT_MS = "group_cooldown_started_at_ms"
    const val KEY_GROUP_COOLDOWN_ENDS_AT_MS = "group_cooldown_ends_at_ms"
    const val KEY_GROUP_COOLDOWN_INCIDENT_ID = "group_cooldown_incident_id"
    const val KEY_GROUP_COOLDOWN_SOURCE_PACKAGE = "group_cooldown_source_package"
    const val KEY_GROUP_COOLDOWN_STARTED = "group_cooldown_started"
    const val KEY_INCIDENT_NEW = "incident_new"
    const val KEY_INCIDENT_ID = "incident_id"
    const val KEY_INCIDENT_OCCURRED_AT_MS = "incident_occurred_at_ms"
    const val KEY_BREAK_SESSION_TOKEN = "break_session_token"
    const val KEY_BREAK_SESSION_EXPIRES_AT_MS = "break_session_expires_at_ms"
    const val KEY_DURATION_MS = "duration_ms"
    const val KEY_DAY_TOKEN = "day_token"
    const val KEY_LAUNCH_INCREMENT = "launch_increment"
    const val KEY_LIMIT_HIT_INCREMENT = "limit_hit_increment"
    const val KEY_HOOK_VERSION_CODE = "hook_version_code"
    const val KEY_LEVEL = "level"
    const val KEY_EVENT = "event"
    const val KEY_MESSAGE = "message"
}
